# Generated by Django 4.1.2 on 2022-11-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
