# Generated by Django 4.1.2 on 2022-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0002_cloth_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
