# Generated by Django 4.1.2 on 2022-12-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_cart_cloth_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
